baseURL = 'https://neving.pages.dev/'
title = 'Neving'
defaultContentLanguage = 'hr'
enableEmoji = true

enableRobotsTXT = true
enableGitInfo = true
googleAnalytics = ''

[languages]
  [languages.en]
    languageName = 'En'
    contentDir = 'content/en'
    weight = 2
  [languages.hr]
    languageName = 'Hr'
    contentDir = 'content/hr'
    weight = 1