baseURL = 'https://neving.netlify.app/'
languageCode = 'hr'
title = 'Neving'
defaultContentLanguage = 'hr'
paginate = 3
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

[services]
  [services.googleAnalytics]
    ID = ''

[languages]
  [languages.hr]
    languageCode = 'hr'
    languageName = 'Hrvatski'
    contentDir = 'content/hr'
    weight = 1
  [languages.en]
    languageCode = 'en'
    languageName = 'English'
    contentDir = 'content/en'
    weight = 2

[params]
  description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fermentum ligula a mauris laoreet, interdum volutpat magna sollicitudin."
  logo = "favicon.ico"
  licence = "Apache-2.0"
  copyrightYear = '2024'
  dateFormat = "02.01.2006."
  [params.author]
    name = "Mislav Matoković"
    email = 'mislav.mat@hotmail.com'
    
[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"

[frontmatter]
  date = ['date', 'publishDate', 'pubdate', 'lastmod', 'modified']
  expiryDate = ['expiryDate', 'unpublishdate']
  lastmod = [':git', 'lastmod', 'modified', 'date', 'publishDate', 'pubdate']
  publishDate = ['publishDate', 'pubdate', 'date']

[taxonomies]
  category = 'categories'
  tag = 'tags'

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = false
    simple = false
  [privacy.youTube]
    disable = false
    privacyEnhanced = false

[module]
  [module.hugoVersion]
    extended = true
    min = '0.112.0'
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "node_modules/alpinejs/dist"
    target = "assets/alpinejs"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"
  [[module.mounts]]
    source = 'static/images'
    target = 'assets/images'

[build]
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "styles\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js|ts|jsx|tsx)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"